name: metrics svg for readme
on:
  push:
    branches:
      - main
      - master
  schedule:
    # * update everyday
    - cron:  '0 0 * * *'
  workflow_dispatch:
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Isometric commit calender
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isoclander.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
      - name: music
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.music.playlist.svg
          plugin_music: yes
          plugin_music_playlist: ${{ secrets.PLAYLIST_URL }}
          plugin_music_limit: 7
          

      
